#!/bin/bash

# DB2 path
DB2_DIR=${DB2_DIR:-/opt/ibm/db2/V9.7}

#set -x

# Reads the instance directory
readInstDirectory () {
  INSTANCE=$1
  PROFILE_DIR=$(eval echo -e ~${INSTANCE}/sqllib/db2profile)

  # If the profile exist load it.
  if [[ -f ${PROFILE_DIR} ]] ; then
    . ${PROFILE_DIR}

    # Checks if DB2 is accessible.
    DB2_EXIST=$(which db2)
    if [[ -x "${DB2_EXIST}" ]] ; then

      db2 terminate > /dev/null 2>&1
# TODO show the number of nodes in the directory
      echo " Nodes:"
      db2 list node directory | tail -n +6 | awk '/^Node / {if (NR!=1) print ""; next} {printf $0} END {print "";}' | awk '{print $4,$17,$21}'
# TODO show the number of dbs in the directory
      echo "  Local databases"
      db2 list db directory | tail -n +6 | awk '/^Database /  {if (NR!=1) print ""; next} {printf $0} END {print "a";}' | awk '/Indirect/ {print $4,$8,$13}'
      echo "  Remote databases"
      db2 list db directory | tail -n +6 | awk '/^Database /  {if (NR!=1) print ""; next} {printf $0} END {print "a";}' | awk '/Remote/ {print $4,$8,$12}'
    else
      echo "DB2 has not been found at instance ${INSTANCE}"
    fi
  else
    echo "${INSTANCE} does not exist"
  fi
}

# Checks if db2greg exist.
if [[ -f ${DB2_DIR}/bin/db2greg ]] ; then
  DB2GREG=${DB2_DIR}/bin/db2greg
else
  echo "DB2 binaries (DB2GREG) location unknown."
  exit 1
fi

echo "Reading db2greg"
echo ${DB2GREG} -dump
while read LINE ; do
  #echo " Instance: $LINE"
  readInstDirectory $LINE
done < <(${DB2GREG} -dump | awk -F, '/^I,DB2/ {print $4}')


