#!/bin/bash
# The MIT License (MIT)
#
# Copyright (c) 2014 Andres Gomez Casanova
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Install the certificate and the authorized keys in a given server.
# This should be executed as the user to access the remote servers.
#
# This script will deploy files in the following directories in the clients:
#
#  * ~/db2-shared/  Directory for all files.
#  * ~/db2-shared/conf/  Configuration files.
#
# 2013-06-07 A. GOMEZ - Creation.

CLIENT=$1
# The next line should be hardcoded in order to ensure there is just one
# server.
SERVER=IBEE-04

SERVER_DIR=~/db2-shared/
SHARED_DIR=db2-shared/
HOSTNAME=$(hostname | cut -d'.' -f 1)

if [[ ${HOSTNAME} != ${SERVER} ]] ; then
 echo "Invalid server: ${HOSTNAME}"
 echo "It should be executed only from server ${SERVER}."
 echo "Call 'install' to install a new server."
elif [[ ${CLIENT} == "" ]] ; then
 echo "The first param is the server to install"
else
 echo "Modify 'servers' file in ~/db2-shared/conf/ directory"
 echo "Make sure you can login into the server (user/password)"
 read -p "Press [Enter] key to continue..."
 ssh ${CLIENT} "mkdir ${SHARED_DIR}"
 rsync -avz ${SERVER_DIR} ${CLIENT}:${SHARED_DIR}
fi

