#!/bin/bash
# The MIT License (MIT)
#
# Copyright (c) 2014 Andres Gomez Casanova
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Uploads the shared directory to the server.
#
# It requires the following directories.
#
#  * ~/db2-shared/  For all files.
#  * ~/db2-shared/conf  Configuration files.
#  * ~/backup/  To keep a history of files.
#
# 2013-06-07 A. GOMEZ - Creation.
# 2013-06-13 A. GOMEZ - No legal output.

# The next line should be hardcoded in order to ensure there is just one
# server.
SERVER=IBEE-04
SERVER_DIR=~/db2-shared/
HOSTNAME=$(hostname | cut -d'.' -f 1)
LOCAL_DIR=~/db2-shared/
REMOTE_DIR=db2-shared
BACKUP_DIR=~/backup
DATE=$(date +"%Y%m%d%H%M%S")

command1 () {
 ssh ${SERVER} tar zcf ${BACKUP_DIR}/upload-${DATE}-${HOSTNAME}.tar ${REMOTE_DIR}
}
command2 () {
 rsync -avz --delete ${LOCAL_DIR} ${SERVER}:${REMOTE_DIR}
}
filter () {
  grep -v -f ${SERVER_DIR}/conf/legal | grep -v '^$'
}

echo "Creating version in server..."
{ command1 2>&1 1>&3 | filter 1>&2; } 3>&1
echo "Synchronizing with server..."
{ command2 2>&1 1>&3 | filter 1>&2; } 3>&1

